W5D2/reddit_clone/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :session
  resources :subs
  resources :posts do
    resources :comments
  end

  resources :comments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W5D2/reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W5D2/reddit_clone/app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, :user, :post, presence: true

  belongs_to :user
  belongs_to :post
  belongs_to :comment, optional: true

  has_many :comments,
  primary_key: :id,
  foreign_key: :parent_comment_id,
  class_name: Comment


end

W5D2/reddit_clone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :user, presence: true

  belongs_to :user
  has_many :post_subs

  has_many :subs,
  through: :post_subs,
  source: :sub

  has_many :comments
end

W5D2/reddit_clone/app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :sub_id, :post_id, presence: true

  belongs_to :post
  belongs_to :sub

end

W5D2/reddit_clone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, :user, presence: true

  belongs_to :user
  has_many :post_subs

  has_many :posts,
  through: :post_subs,
  source: :post
end

W5D2/reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :password_digest, :session_token, presence: true
  validates :username, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :subs
  has_many :posts
  has_many :comments

  attr_reader :password

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    @user && @user.is_password?(password) ? @user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end
end

W5D2/reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token
  end

  def sign_out
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def require_sign_in
    redirect_to new_session_url unless signed_in?
  end
end

W5D2/reddit_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :require_sign_in

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id]
    @comment.save
    flash[:errors] = @comment.errors.full_messages
    if @comment.parent_comment_id == nil
      redirect_to post_url(@comment.post)
    else
      redirect_to post_comment_url(post_id: @comment.post, id: @comment.parent_comment_id)
    end
  end

  def show
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
  end

  def destroy

  end

  private

  def comment_params
    params.require(:comment).permit(:content, :parent_comment_id)
  end

end

W5D2/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_sign_in

  def new
    @post = Post.new
    @subs = Sub.all
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      params[:post][:sub_ids].each do |id|
        PostSub.create(post_id: @post.id, sub_id: id)
      end
      redirect_to post_url(@post)
    else
      @subs = Sub.all
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show

    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update_attributes(post_params)
      @post_subs = PostSub.select("*").where(post_id: params[:id])
      @post_subs.each do |post_sub|
        post_sub.destroy
      end

      params[:post][:sub_ids].each do |id|
        PostSub.create(post_id: @post.id, sub_id: id)
      end
      redirect_to post_url(@post)
    else
      @subs = Sub.all
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_id:[])
  end
end

W5D2/reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid login info"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end
end

W5D2/reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_sign_in

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

W5D2/reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    redirect_to users_url if current_user.id.to_s != params[:id]
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    redirect_to users_url if current_user.id.to_s != params[:id]
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W5D2/reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

W5D2/reddit_clone/app/helpers/comment_helper.rb
module CommentHelper
end

W5D2/reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

W5D2/reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D2/reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

W5D2/reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

W5D2/reddit_clone/app/views/comments/show.html.erb
<h2>Comment</h2>
<% if @comment.parent_comment_id %>
<%= link_to "Previous Comment", post_comment_url(post_id: @post, id: @comment.parent_comment_id) %>
<% else %>
<%= link_to "Back to Post", post_url(@comment.post) %>
<% end %>
<br>
<%= @comment.content %>

<h3>Comments</h3>
<% @comment.comments.each do |comment| %>
  <li><%= link_to comment.content, post_comment_url(post_id: @post, id: comment) %> (<%= comment.comments.count %>)</li>
<% end %>

<h2>Add Comment</h2>
<form class="" action="<%= post_comments_url(@comment.post) %>" method="post">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Comment:
  <input type="text" name="comment[content]" value="">
  </label>
  <input type="submit" name="" value="Add Comment">
</form>

W5D2/reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="header">
      <section>
        <%= button_to "Subs", subs_url, method: :get %>
      </section>

      <section>
        <% if signed_in? %>
        Welcome, <%= link_to current_user.username, user_url(current_user) %>
        <%= button_to "Log Out", session_url, method: :delete %>
        <% else %>
        <%= button_to "Sign In", new_session_url, method: :get %>
        <%= button_to "Sign Up", new_user_url, method: :get %>
        <% end %>
      </section>
    </header>

    <% flash[:errors].try(:each) do |err| %>
    <%= err %>
    <% end %>

    <%= yield %>
  </body>
</html>

W5D2/reddit_clone/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

W5D2/reddit_clone/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

W5D2/reddit_clone/app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<form class="" action="<%= post_url(@post) %>" method="post">

  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label>Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>

  <% @subs.each do |single_sub| %>
    <label><%= single_sub.title %>
      <input
        type="checkbox"
        value="<%= single_sub.id %>"
        name="post[sub_ids][]"
        <%= "checked" if @post.sub_ids.include?(single_sub.id) %>
      />
    </label>
  <% end %>

  <input type="submit" name="" value="Edit Post">
</form>

W5D2/reddit_clone/app/views/posts/new.html.erb
<h2>New Post</h2>
<form class="" action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="">
  </label>

  <label>Content
    <input type="text" name="post[content]" value="">
  </label>

  <% @subs.each do |single_sub| %>
    <label><%= single_sub.title %>
      <input
        type="checkbox"
        value="<%= single_sub.id %>"
        name="post[sub_ids][]"
        <%= "checked" if @post.sub_ids.include?(single_sub.id) %>
      />
    </label>
  <% end %>

  <input type="submit" name="" value="Create Post">
</form>

W5D2/reddit_clone/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<br>
Author: <%= @post.user.username %>
<br>
URL: <%= @post.url %>
<br>
Content:
<br>
<%= @post.content %>

<br>

<%= button_to "Edit Post", edit_post_url(@post), method: :get %>

<h2>Subs</h2>
<% @post.subs.each do |sub| %>
  <li class="subs"><%= link_to sub.title, sub_url(sub) %></li>
<% end %>

<br>
<h2>Comments</h2>
<% top_level = @post.comments.where(parent_comment_id: nil) %>
<% top_level.each do |comment| %>
  <li><%= link_to comment.content, post_comment_url(post_id: @post, id: comment) %> (<%= comment.comments.count %>)</li>
<% end %>
<br>

<h2>Add Comment</h2>
<form class="" action="<%= post_comments_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Comment:
  <input type="text" name="comment[content]" value="">
  </label>
  <input type="submit" name="" value="Add Comment">
</form>

W5D2/reddit_clone/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>